### ISSUE TITLE
TXSourceSummarizer

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/TXPipe#1]
If I understand the pipeline diagram correctly, this component produces an estimate of the redshift distribution n(z) given a set of redshift PDFs (and some information about how they were made, namely the interim prior) that have already been selected based on pre-defined tomographic bins.  

I have an interest in making sure this is done using the [CHIPPR](https://github.com/aimalz/chippr) probabilistic graphical model.  The to-dos below assume we'll use my existing `chippr` code, but the model is general, and I can't say it wouldn't benefit from re-implementation by a better programmer.  

`chippr` is already in a state sufficient for a placeholder, so I can just write a wrapper for it in the format TXPipe needs once that's established.  Otherwise, there are three major tasks that need to be completed, namely upgrading to Python 3.6, scaling up the catalog size (aimalz/chippr#60), and implementing MPI functionality (aimalz/chippr#70).

I'm overcommitted so would benefit from a timetable.  Also, let me know if I've missed something, particularly with respect to the scope of this component and its inputs/outputs.

**Comment by joezuntz** [comment]
@aimalz Thanks so much for joining in!

I was thinking of a month or so timescale, if that works for you?

But I'm very aware of how many things you volunteer for, so maybe getting a a second person in to work with you would be useful?  The 3.6 and MPI issues you mention might be doable easily by others, once the basic wrapper exists.  As would some of the basic TXPipe plumbing stuff.

**Comment by joezuntz** [comment]
@aimalz has to focus on thesis-ready projects for now so won't be able to do this short term.

So I'll put in a temporary stacking approach (sorry @aimalz!) until then.

**Comment by aimalz** [comment]
Yup, sorry about flaking (for now)!  As long as the stacking is in a distinct module, we should be able to swap it out for one using `chippr` when it's ready.

**Comment by aimalz** [comment]
Quick update: the CHIPPR paper is now close enough to convergence that getting the code to run at scale is at the top of the to-do list for the code.

**Comment by EiffL** [comment]
Hi Both, is this still an active task? just to check how we should classify this issue

**Comment by joezuntz** [comment]
Update: the RAIL team is working on summarizers, and we have an internal version ported from the HSC branch in PR here: #233

**Comment by joezuntz** [comment]
This is now exposed in TXPipe in PR #247
