### ISSUE TITLE
TXSelector with a lens sample

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/TXPipe#10]
TXSelector needs to include a lens sample.  Eli is working on a python translation of the redmagic tools - this will be finished after summer.  Need something temporary in the mean time.

**Comment by rmandelb** [comment]
Maybe just the BOSS CMASS and LOWZ color cuts, to make CMASS- and LOWZ-like photometric samples as a simple test case?  The would give you a red sample that goes from z~0.15 to 0.7, which is not what we ideally want but is at least simple and well-defined?

**Comment by joezuntz** [comment]
Nice, thanks!  Seems to be described here:
http://www.sdss3.org/dr9/algorithms/boss_galaxy_ts.php

**Comment by rmandelb** [comment]
Yes, that's correct.  It's a bright and low number density sample, quite a bit brighter than what Eli will produce with redmagic.  But it's not bad as a place holder.

**Comment by rmandelb** [comment]
LOWZ selection was implemented in DESCQA by @EiffL here: https://github.com/LSSTDESC/descqa/blob/ca3025c/descqa/DeltaSigmaTest.py#L43 (lines 43-49).  It would not be hard to use similar lines of code to implement the CMASS cuts that @joezuntz linked to.  The harder part may be making sure you have the right outputs from DM (forced cmodel magnitudes, extinction-corrected) on which to impose the cuts!

**Comment by joezuntz** [comment]
This is all done now - once Eli's RedMagic code is ready we can maybe move to that.
