### ISSUE TITLE
Accept shear_prefix in TXNoiseMaps

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/TXPipe#107]
Currently, `TXNoiseMaps` breaks if a non-metacal-like catalog is passed along. I think that the fix would be just to add `shear_prefix` as a configuration parameter (as in other stages that would have to be run prior to this).

**Comment by joezuntz** [comment]
Thanks - I'll have a look at this.  I'd like to avoid adding configuration where we can avoid it, so I added a heuristic check of what type a catalog is - a function called `read_shear_catalog_type` we can use that.

**Comment by joezuntz** [comment]
This should be fixed a while back with the `get_primary_catalog_names` method
