### ISSUE TITLE
Shear catalog type duplicity

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/TXPipe#110]
It seems like this can be defined either in the [catalog](https://github.com/LSSTDESC/TXPipe/blob/51076382caab4c72508fd96b1eb39c69199fadb6/txpipe/source_selector.py#L77) or in the [config](https://github.com/LSSTDESC/TXPipe/blob/51076382caab4c72508fd96b1eb39c69199fadb6/txpipe/source_selector.py#L103)

**Comment by joezuntz** [comment]
The line `shear_catalog_type = read_shear_catalog_type(self)` also sets the value in the config dict after reading it from the catalog, as well as returning it.  So it's in the config dict, but not the config file.

I know that's surprising; it was partly for backwards compatibility.  Better suggestions welcome!
