### ISSUE TITLE
Two point Fourier for lensfit type calibration

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/TXPipe#116]
Currently in https://github.com/LSSTDESC/TXPipe/blob/master/txpipe/twopoint_fourier.py#L526 the assumption is that metacal calibration/response is used, but if non-metacal shears are created, the metadata necessary for this is not read/the program breaks because it doesn't find `R_gamma_mean`.

**Comment by joezuntz** [comment]
This is now fixed - the calibration is now applied to the maps rather than the spectra, and the variables read in here have been removed.
