### ISSUE TITLE
Laptop installation instructions for macos.

### ISSUE THREAD

**Issue by eacharles** [LSSTDESC/TXPipe#137]
The installation instructions in the README.md  ( to simply use pip install -r requirements.txt) leave out a bunch of stuff that users will need.   
Working from the .travis.yml and using homebrew installed TxPipe on my home computer (mac os 10.15.5).

Here is what I had to do.   I'm not sure what the best way to deal with this is.  We might want to consider some sort of install script for the package.   Or we might just expand the README.md to tell people how to get the system requirements so (i.e., the stuff they need before pip install -r requirements.txt will work).

```
# Install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# Install compilers and such
brew install gsl open-mpi openblas fftw 
brew install autoconf automake libtool swig

# Make a conda env for txpipe (this assume that conda is already available)
conda create -y --name txpipe-py37 python=3.7 numpy
conda activate txpipe-py37

# Pip install requirements
pip install git+git://github.com/LSSTDESC/CCL@a9c23144727768a91af76da0c727830e6f0ed784
pip install --no-binary=mpi4py -r requirements.txt

# This only works with conda, do it hear once all the other stuff is installed via pip
conda install -n txpipe-py37 -c conda-forge namaster

# tests
ceci examples/laptop_redmagic_pipeline.yml
ceci examples/laptop_lensfit_pipeline.yml
```

**Comment by cwwalter** [comment]
@eacharles 

Nice, I also posted in the 3x2pt (on May 12th) channel a way to do based just on conda so you could create and throw away an environment with no other dependencies.

```
conda create --yes --name 3x2pt
conda activate 3x2pt
conda install --yes h5py pandas matplotlib healpy threadpoolctl scikit-learn astropy
conda install --yes sacc pyccl camb cosmosis-standalone
conda install --yes treecorr firecrown
conda install --yes flask ruamel.yaml psutil parsl
pip install --no-deps mlz_desc 
pip install --no-deps tjpcov
pip install --no-deps cwlgen
pip install --no-deps git+git://github.com/LSSTDESC/ceci@v0.2#egg=ceci
pip install --no-deps git+git://github.com/LSSTDESC/gcr-catalogs#egg=GCRCatalogs
```

I last did this in May so it might need to be tweaked now and some of the pip packages might already be in conda. @beckermr said hew was thinking about that.

**Comment by joezuntz** [comment]
The new conda installer incorporates the work here - many thanks all!
