### ISSUE TITLE
Healpy and fitsio not installing ubuntu

### ISSUE THREAD

**Issue by empEvil** [LSSTDESC/TXPipe#18]
I tried to install healpy and fitsio on ubuntu. using the following command:  pip3 install healpy fitsio
and I get the following error message

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-z_pbwhi5/healpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-gw1cnmja-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-z_pbwhi5/healpy/

**Comment by joezuntz** [comment]
There should be more info above that.

**Comment by empEvil** [comment]
Possible solution:
Update the pip installation, seems that the latest version of pip released broke stuff for older versions. Thanks to Mike for suggesting this.
