### ISSUE TITLE
TXTwoPointReal

### ISSUE THREAD

**Issue by chihway** [LSSTDESC/TXPipe#2]
Here's what I think the expected content of this module:

* Input: 
  - shear catalog
  - galaxy catalog
  - random catalog
  - tomography catalog (flags that assign shear/galaxy into tomographic bins)
  - diagnostic maps

* output: 
  - one file that contains the full data vector (1d array) and meta data (binning information, angular values) 
  - this includes all auto- and cross-correlations for NN (galaxy clustering), NG (galaxy-galaxy lensing) and GG (cosmic shear)
  - think about whether we want to store the intermediate information (DD, RR, DR for NN, weights and calibration for GG and NG)
  - think about whether we will ever want to do jackknifing, in that case the output is different too

Things to think about:
* what's the input and output format?
* how does the meta-info come in to this module: number of bins, angular bins, bslop -- is there a global parameter file that runs through the whole TXPipe?
* how do we want to do the parallel job submission? assuming nersc for now I guess?

@joezuntz, thoughts?

**Comment by joezuntz** [comment]
Hi @chihway - thanks so much for opening this.

It could definitely be useful to save the intermediate info - it's a pretty small amount of data, so I think worth it for the debugging info.

For meta data - some of those quantities should definitely come directly from previous data sets - e.g. the tomographic selector TXSelector should save metadata about the number of tomo bins.

For stuff that first comes in here, like bin_slop and the angular bin choices, I've been using a model where there is one shared configuration file with the tag "config". It's a YAML file with sections corresponding to the names of the different pipeline stages to be run.  Then the self.read_config method on the stages reads everything in that section and returns it as a dict.

You can also optionally add the config_options class variable on the stage to list things that *must* be in that dictionary.

I'll write this up in the documentation - it's more generally useful.

**Comment by joezuntz** [comment]
Forgot to add - for the parallel job submission, the best thing to do now is start an interactive job (http://www.nersc.gov/users/computational-systems/cori/running-jobs/interactive-jobs/) and run from there using the configuration that's in test.yaml.  I'll try to improve how this works as we go along.

For the input formats, the only thing that we know at this stage is the shear catalog, which for now is in the format used here: /Users/jaz/data/hsc/tract008766-shear-cat-0-10000.fits

Other things are kind of up to you!  Maybe stick with HDF for the 2pt data?

**Comment by chihway** [comment]
Ok, thanks @joezuntz ! so @ellongley and I are going to get started on this... one general question: are we writing this assuming metacal to be the default (and only) shear catalog format? or do we have the option of using non-metacal catalogs (eg. protoDC2)?  

Also, is our output is suppose to be SACC format? or that comes in a later stage (together with the covariance)?

**Comment by joezuntz** [comment]
Not sure about the SACC question - I'll leave that to you to evaluate.

**Comment by ellongley** [comment]
Posting a question that has come up: 

At what step in the process will lens galaxies be given? 

@chihway mentioned two possibilities, 

1. An additional catalog for lenses only to input to TwoPointReal

2. The shear catalog will contain all galaxies and TXSelector or another step will add lens/source flags on top of the bin flags. 

Thank you! @joezuntz

**Comment by joezuntz** [comment]
I had a conversation with @slosar yesterday about this. In the long term we need some clever selection method, possibly as part of PZ, but for now we can use redmagic.

So let's assume a new module TXRedMagic - we'll keep it separate from TXSelector as it is doing something a bit different.  So then it will need to make a new catalog file with a lens bin in.

**Comment by damonge** [comment]
Would we want to call it something more generic than that? Presumably we'll want to explore different types of lenses than just redmagic (low number density)

**Comment by joezuntz** [comment]
Yep - the generic box is some kind of general TXLensSelector name, but this specific class implementation can be named after its own implementation

**Comment by joezuntz** [comment]
@chihway re: metacal - for now, yes, let's assume all the shear catalogs are metacal

**Comment by joezuntz** [comment]
@damonge @slosar is there some code in LSS somewhere already to do a redmagic selection?

**Comment by damonge** [comment]
Nop. I drop everyone a line on slack in case someone wants to do it, if you want.

**Comment by joezuntz** [comment]
Thanks - that would be v useful.
