### ISSUE TITLE
update the documentation 

### ISSUE THREAD

**Issue by empEvil** [LSSTDESC/TXPipe#202]
The docs are not updated

**Comment by empEvil** [comment]
I have rerun the documentation creation, however seems because of some new imports not all pages have updated correctly. 
so TODO:

- Deal with new imports messing up imports
- Setup continuous integration to automatically update the docs whenever Master is updated

**Comment by joezuntz** [comment]
The imports problem is dealt with in the newest version, but we are still not auto-creating docs - need to set that up.

**Comment by joezuntz** [comment]
They still need a general set of updates, but the docs are now finally getting auto-rebuilt.
