### ISSUE TITLE
Add options to TwoPoint Stage to choose which correlations to run

### ISSUE THREAD

**Issue by jpratmarti** [LSSTDESC/TXPipe#217]
Right now TwoPoint Stage requires to have both a lens and source catalog. For some projects we do not need to run all the correlations. We should add an option to be able to choose which correlations to run, so that it doesn't require all the inputs.

**Comment by joezuntz** [comment]
PR #296 shows how to do this now, with an example showing how to skip the lens sample.

Basically we now set some file inputs to the string "none".
