### ISSUE TITLE
Apply Calibration for TwoPoint Fourier

### ISSUE THREAD

**Issue by ellongley** [LSSTDESC/TXPipe#23]

**Comment by EiffL** [comment]
I *think* this is ok now, right?

**Comment by joezuntz** [comment]
No, still needs doing.  Our current tests have been with R=1

**Comment by EiffL** [comment]
Ah :-D I saw an R matrix in the code and figured that was ok :-) 
But is it something specific to Fourier?

**Comment by joezuntz** [comment]
Yep, they're loaded but not used yet.  

They are used in the real-space calculation.

**Comment by joezuntz** [comment]
This is now applied in the mapping stage
