### ISSUE TITLE
Don't hack around CCL errors 

### ISSUE THREAD

**Issue by tilmantroester** [LSSTDESC/TXPipe#246]
There are a couple of places where CCL integration errors get purposefully ignored. For example https://github.com/LSSTDESC/TXPipe/blob/master/txpipe/theory.py#L87

This should be removed, since CCL master can now handle bad n(z) much better. By using a downsampling value that happened to not cause an error, this also hid erroneous predictions. For example, the cosmic shear prediction for `source_4` is low by a factor of ~2:
![shear_shear_downsample2_window_function_spline_intg](https://user-images.githubusercontent.com/26582252/165777043-38741f14-58f0-4ee3-96b5-872a3001c04e.png)

**Comment by joezuntz** [comment]
This is working now
