### ISSUE TITLE
Source maps are not being created correctly for CosmoDC2 runs. 

### ISSUE THREAD

**Issue by jpratmarti** [LSSTDESC/TXPipe#258]
We suspect it might have to do with the calibration of the maps. I'm getting values of: [4.18312796e-01  1.30356288e-01 -2.32892875e+30 ... -2.32892875e+30
 -1.34839417e-01 -2.32892875e+30]

**Comment by joezuntz** [comment]
I think we fixed this @jpratmarti ?

**Comment by jpratmarti** [comment]
yes!
