### ISSUE TITLE
photoz_stack

### ISSUE THREAD

**Issue by gabygga** [LSSTDESC/TXPipe#268]
Hi there

Are the notebooks still valid?  I'm specially running the: `Welcome to TXPipe` and I updated the input paths, however I don't find the `photoz_stack.hdf5` file.

**Comment by joezuntz** [comment]
Yes - this is out of date.  @jgpaine is looking at writing a new version of this.

**Comment by joezuntz** [comment]
The notebook is working again now and tested in the continuous integration.
