### ISSUE TITLE
TXTesting

### ISSUE THREAD

**Issue by chihway** [LSSTDESC/TXPipe#3]
This is a temporary name for the suite of tests we want to do alongside with the 3x2 pipeline. Not exactly sure where it should live for now, but this issue is to keep in mind that we need something like this somewhere.

**Comment by chihway** [comment]
Here's just pinging people who may have thoughts on this @rmandelb @matroxel @msimet @ellongley @joezuntz @rmjarvis @damonge 

Based on what was said in the telecon regarding DM incorporating null tests, I'd say what we need to think about here are tests that are specific to 3x2 (in terms of the sub-sample in photometric bins, for example). One way to do this is to have another ellipse in parallel with TXTwoPoint

Perhaps it helps to list some null tests that are industry standard (someone can fill in tests for galaxy clustering):
- rho statistics
- consistency between splitting (S/N, size, diagnostic quantities, chip edges)
- B-modes (for shear)
- PSF residual tests

Also related literature:
- https://arxiv.org/pdf/1708.01533.pdf
- https://arxiv.org/pdf/1705.06745.pdf

**Comment by rmjarvis** [comment]
* no gg lensing for source in front of lens (or consistent with z overlap)
* alpha/beta analysis from shear x psf correlations (alpha, beta should be consistent with zero ideally)
* mean whisker plots across field of view (usually evaluated by eye -- should show no structure or features -- but could turn into something more quantitative)
* ditto for PSF residuals from reserved stars not used in fit
* no g-g lensing around non-lensing objects.  E.g. chip centers, field centers, stars, etc.
* consistent cosmology between shear only vs gg + clustering
* cosmology constraints consistent for subsets (e.g. only high- or low-z tomo bins or good mean seeing vs bad mean seeing area, etc.)
* no significant cross correlation between lensing map and various attribute maps (mean seeing, mean airmass, mean psf properties, etc.)

**Comment by rmandelb** [comment]
@chihway - see list of null tests here - https://confluence.slac.stanford.edu/display/LSSTDESC/WL1.5%3A+null+test+pipeline

**Comment by chihway** [comment]
@rmandelb, thanks, sorry I didn't know this exist.

So is there also existing plans/people that are working on this? And should we try to incorporate some of it into TXPipe for DC2?

**Comment by joezuntz** [comment]
We can divide these tests into categories based on the point at which they can be performed.

There are:
1.  Tests that can be done using only the catalogs and other input data.
2.  Tests that require some TXPipe outputs (e.g. tomographic tests)
3.  Tests that need final summary statistics (e.g consistency checks, recovery of correct cosmology)

I think we want to use the same code base for all of these, but call them in different ways.  Group 1 is a large job that should be run as its own job (or pipeline?).  Group 2 should be run as another step in the TX pipeline, but should be written fairly flexibly.  Group 3 should be run along with parameter estimation. 

So I think we want two ways to execute (bits of) the suite: standalone and pipeline.

**Comment by rmandelb** [comment]
@chihway - no, after some discussion this was largely tabled for until there was a pipeline to plug the null tests into.  Troxel and Melanie Simet both have null testing pipelines that you could look into for this?

@joezuntz - I agree.

**Comment by joezuntz** [comment]
I'm going to close this issue and open a new one with an explicit checklist at the top, which we can add to as we go along of course.
