### ISSUE TITLE
CL Interface Step 1: Save to SACC background galaxies for cluster object

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/TXPipe#306]
TXPipe efficiently extracts background galaxies for a given source.  There are currently 3 stages to locate catalogs of background galaxies for cluster mass modeling that can then be used as inputs for CLMM.

The first pipeline stage ingests a cluster catalog (currently redmapper), which critically contains ra/dec and redshift.

The second pipeline stage uses the rlens metric (impact factor between the vector to the source galaxy and the location of the lens as its distance) to measure the 2-point shear. This writes the corresponding source_list, lens_list, and any meta data.

The third pipeline stage selects source galaxies for the cluster catalog by finding galaxies near each cluster, and has functionality to return the CLMM object, GCData.

For increasing levels of complexity, we will need to save the necessary information for CLMM to use, or to pass to yet another stage of the TXPipe pipeline.

Goals:
- [ ] Note - for now, can save GCData as some intermediate format (e.g. HDF5) for CLMM to easily read in and for the user to go to the next pipeline stage.  This offers flexibility for CLMM users to use a TXPipe output of background galaxies and use the background galaxies as they want outside of TXPipe
- [ ] Refer to the 3x2 functionality to see how to best save a SACC file with all necessary info for CLMM GCData catalog → primary necessary information is the selected background galaxies
- [ ] Create code functionality to save the SACC file (could be optional)

**Comment by marina-ricci** [comment]
After discussion, we realized this is not needed (catalogs are in hdf5 format).
