### ISSUE TITLE
CL Interface Step 3: Create pipeline stage to compute and save stacked Cluster Shear Profiles

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/TXPipe#308]
We want TXPipe to construct stacked cluster profiles corresponding to a given richness and redshift bin.

**Open Question**:  Stack the constructed profiles from Step 2 or all the background galaxies from Step 2?

Goals:
- [ ] Create a pipeline stage to construct stacked profiles 
- [ ] Use the cluster bin definition from another piepline stage
- [ ] Save a SACC file with meta data (e.g. richness, redshift bins, clusters in the stack, etc.)

_(written by Camille and modified by Marina)_

**Comment by marina-ricci** [comment]
After discussion, this will be done in Step 2 #307 .
