### ISSUE TITLE
CL example 20 sq degree run on NERSC

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/TXPipe#310]
The example notebook, `txpipe_cluster_background_selection.ipynb` contains a section with instructions for running TXPipe to select cluster background sources on the 20 square degree CosmoDC2 data + mock noise dataset.  There are yaml files and a `.sub` script to submit a job to IN2P3.  But, there is no parallel set of files and instructions for running the same job on NERSC.

Goals:
- [x] Look into example jobs to run on NERSC
- [x] Create an analogous `.sub` script to run `examples/cosmodc2/20deg2-in2p3.sub`
- [x] Check for any differences in necessary yaml files, create new (decide whether to put into subdirectories or same directory)
- [x] Modify `txpipe_cluster_background_selection.ipynb` to include NERSC version of instructions.
- [x] Test

**Comment by joezuntz** [comment]
I've added a [submission script](https://github.com/LSSTDESC/TXPipe/blob/master/examples/cosmodc2/20deg2-nersc.sub) and [pipeline file](https://github.com/LSSTDESC/TXPipe/blob/master/examples/cosmodc2/pipeline-20deg2-clmm-nersc.yml) to the master branch.

**Comment by joezuntz** [comment]
Please do move them around or otherwise do what you like with them!

**Comment by cavestruz** [comment]
Ah, okay - cool, thank you so much!  I'll test this out.

**Comment by cavestruz** [comment]
Quick note - the conda instructions do in fact work.

**Comment by cavestruz** [comment]
Closed with PR #313
