### ISSUE TITLE
I don't understand the TX import logic 

### ISSUE THREAD

**Issue by marina-ricci** [LSSTDESC/TXPipe#315]
This is more of a comment for @joezuntz. I noticed that the way the import are written in the __init__ files, we are often importing all functions without asking it explicitly. Is it a deliberate choice? I find it quite confusing. 

For instance, the `CLClusterShearCatalogs` pipeline stage was imported just from the line `from .extensions.clmm import TXTwoPointRLens` in `/txpipe/__init__`.

**Comment by joezuntz** [comment]
You mean why are we doing `from .clmm import *` and things like that?  I don't think any particular reason, if you'd like to change it please do.

**Comment by joezuntz** [comment]
I think this is okay now?
