### ISSUE TITLE
Switch columns for mcal cut to `mcal_s2n`

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/TXPipe#32]
https://github.com/LSSTDESC/TXPipe/blob/d13bd92581b2819343aa6f08ab3ceed68b661cdf/txpipe/selector.py#L419

According to Erin, the metacal code is no longer evaluating SNRs on rounded versions anymore, so `mcal_s2n_r` is no longer part of the catalog, he recommends instead to use `mcal_s2n` for the SNR cut

**Comment by joezuntz** [comment]
This is done now, along with lots of other renamings.
