### ISSUE TITLE
Bug: reversed input for theory_3x2pt in TXTwoPointTheoryFourier

### ISSUE THREAD

**Issue by hangqianjun** [LSSTDESC/TXPipe#329]
Hi! The two inputs for the function `theory_3x2pt` seems to be reversed in order in the following stage:
https://github.com/LSSTDESC/TXPipe/blob/aba4a1aa779f6ee2639acc08b12be95e51aef2a2/txpipe/theory.py#L98C42-L98C42

**Comment by joezuntz** [comment]
Thanks! Fixing this now in https://github.com/LSSTDESC/TXPipe/pull/330

**Comment by hangqianjun** [comment]
Hi @joezuntz! When this change is fixed, would it also be updated on the nersc environment if I'm using `source /global/cfs/cdirs/lsst/groups/WL/users/zuntz/setup-txpipe`

**Comment by joezuntz** [comment]
Yes, once you do "git pull".  I have to fix something else that I broke this morning first though!

**Comment by hangqianjun** [comment]
> Yes, once you do "git pull". I have to fix something else that I broke this morning first though!

Sorry I was a bit confused - I'm using the pre-set txpipe environment on nersc rather than installing from github. Would the former work as well? Or maybe I'm have some misunderstanding here.

**Comment by joezuntz** [comment]
The setup-txpipe command only sets up the dependencies that TXPipe needs - the actual code itself you have to clone yourself.

**Comment by hangqianjun** [comment]
Ah yes I got things mixed up!! Sorry!!! Thanks! :)

**Comment by joezuntz** [comment]
The fix for this is now merged.
