### ISSUE TITLE
Update the test des-y3 file 

### ISSUE THREAD

**Issue by yomori** [LSSTDESC/TXPipe#334]
The current example test file does not have  _1p _1m _2p _2m columns for the `weight` variable.
This is needed to pass the `TXSourceSelectorMetacal` stage, otherwise it prints out:
`KeyError: "Unable to synchronously open object (object 'weight_1p' doesn't exist)"`.
Do you mind updating the file that gets automatically downloaded during testing?

**Comment by joezuntz** [comment]
Done - I've just re-run the jobs that failed from this.

**Comment by joezuntz** [comment]
The actions that failed before have passed now, so this is done.
