### ISSUE TITLE
Harmonize columns names with official DPDD values and GCR metacal catalog

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/TXPipe#34]
Looking at the code, there are many places where the names of the various fields are deviating from the upstream standard being developed by the Data Access Task Force.

For instance, one example that caught my eye is  `mag_true_i_lsst` which doesnt exist, instead `mag_i_cModel` should be used, as define here:  https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/catalog_configs/_dc2_object_meta.yaml 
Same goes for a few metacal columns, and I assume photo-z columns

We should try to do this harmonization sooner rather than later...

**Comment by joezuntz** [comment]
This is done in a recent merge.

**Comment by joezuntz** [comment]
(accidentally close wrong issue)

**Comment by joezuntz** [comment]
In the end we went for simplicity in the names used internally within TXPipe, also on the basis that we've been (and will be) using external data where the LSST names don't make sense. So I'll close this.
