### ISSUE TITLE
build issue with conda

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/TXPipe#42]
I tried to have a complete conda install of TXPipe in a separate environment at CC-IN2P3. The following sequence *almost* work:

> cd /pbs/throng/lsst/users/tanugi/software/desc_pipelines/txpipe_conda/
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh 
./miniconda3/bin/activate 
conda install cmake
conda install gxx_linux-64
conda install -c conda-forge namaster
pip install ceci
pip install gcr
git clone https://github.com/LSSTDESC/gcr-catalogs.git
cd gcr-catalogs/
python setup.py install
cd ..
git clone https://github.com/LSSTDESC/TXPipe
cd TXPipe/
pip install -r requirements.txt

The problem then is that pyccl does not find fftw3 include and lib files..... They are there, because namaster install did put them in the conda internal dirs, but I did not manage to get pyccl to look at it automatically, though for instance I did try without success `pip install --global-option=build_ext --global-option="-I/pbs/throng/lsst/users/tanugi/software/desc_pipelines/txpipe_conda/miniconda3/include" --global-option="-L/pbs/throng/lsst/users/tanugi/software/desc_pipelines/txpipe_conda/miniconda3/lib" --no-clean pyccl`

**Comment by joezuntz** [comment]
You might be able to add the relevant directories to LD_LIBRARY_PATH and C_INCLUDE_PATH?  That is a bit of a hack though.

**Comment by EiffL** [comment]
@johannct Would you be ok with us closing this for now? We will keep working on making TXPipe run smoothly, but a lot has changed since last year.

**Comment by cwwalter** [comment]
@johannct Take a look at my post in desc-3x2pt yesterday on building a conda environment.  It might help you:

This assumes you are preferring conda-forge with strict-channels.

```
conda create --yes --name 3x2pt
conda activate 3x2pt
conda install --yes h5py pandas matplotlib healpy threadpoolctl scikit-learn astropy
conda install --yes sacc pyccl camb cosmosis-standalone
conda install --yes treecorr firecrown
conda install --yes flask ruamel.yaml psutil parsl

pip install --no-deps mlz_desc 
pip install --no-deps tjpcov
pip install --no-deps cwlgen

pip install --no-deps git+git://github.com/LSSTDESC/ceci@v0.2#egg=ceci
pip install --no-deps git+git://github.com/LSSTDESC/gcr-catalogs#egg=GCRCatalogs
```

**Comment by joezuntz** [comment]
Think this is out of dat now - closing.
