### ISSUE TITLE
Metadata in metacal output

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/TXPipe#5]
Hi Erin.

It looks like the metacal output FITS file doesn't currently store any info on which bands were used in the fitting, so it's not possible to tell what the different sub-columns in the mcal_mag column mean (e.gl which one is which band).

Could you add that info to the header so we can tell which column we should be using?  
Or am I wrong and it's there somewhere already?

In the long run this may be in DM, but for the next few years we need it.

Cheers,
Joe

**Comment by esheldon** [comment]
Yes, I can add this next time.

they are always going to be ordered by wavelength.  If there are 3 bands  it will definitely be `riz`.

**Comment by joezuntz** [comment]
The structure of mcal output has now changed to the point where this is not needed.
