### ISSUE TITLE
Feedback from TAMU Sprint Week 

### ISSUE THREAD

**Issue by ellongley** [LSSTDESC/TXPipe#53]
I'm collecting here some things that come up at Sprint week from others using the pipeline, we can add and split to separate issues, but just want to keep track. 

* Regarding SACC data, the bin edges should be saved in the metadata (not just the n(z)s 
* Also the metadata is currently commented out in master so the SACC files don't have it stored.

**Comment by chihway** [comment]
**Problems in installation/running:**
* Complaining about parsl (ModuleNotFoundError: No module named 'parsl.config'). Solution: pip uninstall parsl/ceci
* Failing on the stage where it looks for the git diff information

**Functions/capabilities that can be added to make TXPipe more usable:**
* Multiple lens planes (how would we do selection in TXSelector)
* Spell out more specifically what is what in the TXSelector parameters, also allow for selecting flag?
* Make it easy to use separate lens file (this is likely going to be the default anyway, right?)
* Do we want to measure boost factors in the diagnostics or just part of the measurements?

**Comment by MariaElidaiana** [comment]
**Functions/capabilities that can be added to make TXPipe more usable:**

- Is there a plan to apply a blinding scheme to the data-vector?

**Comment by EiffL** [comment]
Hi everyone, if some of these items are still relevant and very much needed, could you convert them to  issues? To make it easier to track individual improvements needed :-) And then we may close that issue ;-)

**Comment by chihway** [comment]
I think you can close this, most are in issues or irrelevant now

**Comment by joezuntz** [comment]
Yep, I think these are mostly elsewhere now.  Boost factors is one thing that isn't, and we could do with collating a list of other things to measure, including that.
