### ISSUE TITLE
composite use should not define what column to order on, at the user level

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/TXPipe#56]
https://github.com/LSSTDESC/TXPipe/blob/af9c9d5a09b257b4a6c467d5c6695265614f2749/txpipe/metacal_gcr_input.py#L256

In this specific case, `id` has been removed from the metacal file (see https://github.com/LSSTDESC/DC2-production/blob/d9380973d08152ba8e7948eda3d3afe0f36b4caf/scripts/make_metacal_catalog.py#L145) and thus TXGCRTwoCatalogInput is currently broken for DC2 Run2.2i

**Comment by EiffL** [comment]
@maho3 this is why we have different maps

**Comment by joezuntz** [comment]
Fixed in f16c8576e11bda9e62412086857c737265feb7ac
