### ISSUE TITLE
Add support for non metacal shear in TXPipe

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/TXPipe#62]
For the purpose of  the reanalyis projects, we want to be able to use non metacal data shape catalogs. We can either fake metacal at the input stage and then not touch anything else afterwards.... or add proper support for "shear catalog", and make TXPipe smoothly handle both cases.

I'm going to try to implement the second option in: `u/EiffL/shear_catalog`

Thoughts and idea are welcome! In particular, a lot of metacal stuff is hardcoded all over TXPipe at the moment, so making the code more generic is going to involve a lot of modifications....

**Comment by joezuntz** [comment]
Basic support is now merged. More things may come up, which we can open more issues for.
