### ISSUE TITLE
Add multiple (external) lens bins

### ISSUE THREAD

**Issue by chihway** [LSSTDESC/TXPipe#65]
We want to have the capability of using e.g. redmagic for the lenses. That is, 1) there are multiple bins and 2) they come with given redshift 3) txpipe config should include parameters that specify the lens redshift binning

**Comment by fjaviersanchez** [comment]
@joezuntz would it be sensible to split `TXSelector` in two separate tasks `TXSourceSelection` and `TXLensSelection`?

**Comment by aimalz** [comment]
I haven't thought about how it propagates into TXPipe design, but I think the plan for [the project to make a pipeline element that optimizes bin assignments](https://confluence.slac.stanford.edu/display/LSSTDESC/TXSelector%3A+optimizing+the+tomographic+binning+strategy) could do both simultaneously.

**Comment by joezuntz** [comment]
@fjaviersanchez sorry not to reply to this ages ago - yes, splitting into two is useful.  @aimalz , I think the step you're describing can be developed in parallel to this and may replace them later.  

At the very least the selectors need to choose which objects can be considered for different lens tomo and source bins.

**Comment by chihway** [comment]
separate into two scripts: 
lens_selector.py, source_selector.py, each with its own class

source (@chihway):
- not much change, just the option of non-mcal = input pz
- test random forest performance

lens (@fjaviersanchez ):
- similar option of input pz
- keep cmass/lowz? as an option, add more general stuff (mag-lim etc)
- extend to include more lens bins
