### ISSUE TITLE
Incorporate Gaussian covariance in real and harmonic space from TJPCov

### ISSUE THREAD

**Issue by chihway** [LSSTDESC/TXPipe#66]
Building on `covariance.py`, add a stage after `TXTwoPoint` that calls TJPCov and generates a covariance.

**Comment by chihway** [comment]
Starting new branch `gaussian_covariance` for this.

**Comment by chihway** [comment]
Some notes:
* currently we have TXFourierGaussianCovariance class, should we just do TXGaussianCovariance since the reals-ace covariance require to calculate the harmonic space covariance first before Wigner Transforming? or do two separate stages?
* for real-space, we read in a real-space sacc file, need to come up with some ell binning 
* how should we connect to TJPCov, really we just need the wigner_transform.py file for now

**Comment by chihway** [comment]
Ok I have something that runs through that is certainly wrong... 

@joezuntz @EiffL @fjaviersanchez a couple more specific questions as this starts taking place:
1.  reminder to work on the TJPCov interface, currently it's clearly a hack
> import sys
> sys.path.append("../TJPCov")
> from wigner_transform import *
2. what's a good place to save metadata such as fsky/ell binning? we need them for covariance calculation and in the example in https://github.com/LSSTDESC/TJPCov/blob/master/Gaussian_cov-DES.ipynb it was stored in the "metadata" attribute of the sacc file, but if I try to do the same that throws an error when I save sacc

**Comment by joezuntz** [comment]
Hi all.

> currently we have TXFourierGaussianCovariance class, should we just do TXGaussianCovariance since the reals-ace covariance require to calculate the harmonic space covariance first before Wigner Transforming? or do two separate stages?

Let's make them two separate stages, one a subclass of the other, since then we can re-use lots of the stuff, without merging the twopoint and twopoint_fourier tags (we might want to run both of them in the same pipeline to get both outputs).

**Comment by chihway** [comment]
ok will do! I'll also change some of the file names that contain "twopoint" to "twopoint_real" just to be specific.

I was able to extract the ell binning from the window function in the sacc files, however, there seems to be a bug and the min and max attributes seems to be storing the window function itself. If that was meant to be then we should probably change the min/max names.

>>> A = sacc.Sacc.load_fits('twopoint_data_fourier.sacc')
>>> A.data[10]['window'].min
array([2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639, 2640, 2641, 2642,
       2643, 2644, 2645, 2646, 2647, 2648, 2649, 2650, 2651, 2652, 2653,
       2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663, 2664,
       2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674, 2675,
       2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685, 2686,
       2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696, 2697,
       2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707, 2708,
       2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718, 2719,
       2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729, 2730,
       2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740, 2741,
       2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751, 2752,
       2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762, 2763,
       2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 2772, 2773, 2774,
       2775, 2776, 2777, 2778, 2779, 2780, 2781, 2782, 2783, 2784, 2785,
       2786, 2787, 2788, 2789, 2790, 2791, 2792, 2793, 2794, 2795, 2796,
       2797, 2798, 2799, 2800, 2801, 2802, 2803, 2804, 2805, 2806, 2807,
       2808, 2809, 2810, 2811, 2812, 2813, 2814, 2815, 2816, 2817, 2818,
       2819, 2820, 2821, 2822, 2823, 2824, 2825, 2826, 2827, 2828, 2829,
       2830, 2831, 2832, 2833, 2834, 2835, 2836, 2837, 2838, 2839, 2840,
       2841, 2842, 2843, 2844, 2845, 2846, 2847, 2848, 2849, 2850, 2851,
       2852, 2853, 2854, 2855, 2856, 2857, 2858, 2859, 2860, 2861, 2862,
       2863, 2864, 2865, 2866, 2867, 2868, 2869, 2870, 2871, 2872, 2873,
       2874, 2875, 2876, 2877, 2878, 2879, 2880, 2881, 2882, 2883, 2884,
       2885, 2886, 2887, 2888, 2889, 2890, 2891, 2892, 2893, 2894],
      dtype=int32)
>>> A.data[10]['window'].max
array([0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228, 0.00380228, 0.00380228,
       0.00380228, 0.00380228, 0.00380228])

**Comment by chihway** [comment]
![image](https://user-images.githubusercontent.com/2736097/74386950-ecc8e280-4dbc-11ea-8775-61b8b28a7405.png)

Log10 of current Fourier covariance... 

Todo next:
* update lens selection so that number count is not zero
* real-space sub-class
* add bias and IA into input (?)
* compare with cosmosis
* test pos-defness

**Comment by chihway** [comment]
Looking at https://github.com/LSSTDESC/TXPipe/blob/master/txpipe/utils/number_density_stats.py

```
lens_counts = np.zeros_like(self.lens_counts)
        if self.comm is not None:
            import mpi4py.MPI
            self.comm.Reduce(
                [self.lens_counts, mpi4py.MPI.DOUBLE],
                [lens_counts, mpi4py.MPI.DOUBLE],
                op = mpi4py.MPI.SUM,
                root = 0
            )
```
What is this doing? seems like it's always giving zero lens counts and not sure why it is needed...

**Comment by joezuntz** [comment]
It sums the `self.lens_counts` from the different processes into `lens_counts`.  Or possibly if I've got the order of the arguments the wrong way around, it's possible that it's summing lots of zeros together.

**Comment by joezuntz** [comment]
No, looks like it's in the right order; the function signature is: `Comm.Reduce(self, sendbuf, recvbuf, Op op=SUM, int root=0)`

It might be wrong if the counts are actually integers.  Are you seeing them coming out as zeros?

**Comment by chihway** [comment]
Yep they are zeros and throwing off the covariance stuff.

**Comment by joezuntz** [comment]
I see the error.  It works under MPI but not otherwise.  Fixing now.

**Comment by joezuntz** [comment]
Fix pushed to master

**Comment by chihway** [comment]
Thanks!!

**Comment by chihway** [comment]
Ok, there is a version that runs in that it produces real and Fourier gaussian covariances. Still to  do:
* real space only has xi+ for shear-shear
* TJPCov is still awkwardly imported, and need to add p.close() for multiprocess on nersc
* error in sacc -- window function min max is currently wrong
* add IA/bias -- this is going to be input??
* theta min/max is now read in awkwardly, should be stored in sacc from twopoint.py
* kind of hard to tell whether the output makes sense since the area is tiny and the measurements are are really noisy

![image](https://user-images.githubusercontent.com/2736097/75312664-4949ea00-5820-11ea-916a-0aa18d3a02ec.png)

**Comment by joezuntz** [comment]
I'm just testing a fix for the sacc error now.  If it works I'll push it to master as well as my branch.

For the import, I would leave out the sys.path bit and just require the user to have it on their PYTHONPATH.  That's easy enough to do for the docker/shifter version.  In the long run we want to have TJPCov pip-installable I assume (it's v easy to do that).

For the IA/bias - we need to upgrade CCL's tool for saving a cosmology (which was my quick and dirty contribution) to save something a bit more complete.  Or possibly even switch to using FireCrown to evaluate the model, if we're going to have a bunch of systematics in it?  Let's pint that for now.

**Comment by joezuntz** [comment]
fix pushed for the sacc thing

**Comment by chihway** [comment]
Thanks Joe! I've created a pull-request on this.
