### ISSUE TITLE
Add NaMaster covariances?

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/TXPipe#96]
I saw that the covariances in Fourier space are computed internally in TXPipe but, since the power-spectra are computed already with NaMaster, maybe we could also compute the covariances with NaMaster, which already takes into account the coupling between modes?

Looking for volunteers for this.

**Comment by fjaviersanchez** [comment]
@hocamachoc was interested in addressing this issue. Please feel free to assign it to yourself as you see fit :)

**Comment by joezuntz** [comment]
I've made a start on this, though no idea if it works at all! 
https://github.com/LSSTDESC/TXPipe/tree/namaster-cov

If you were interested in taking this forward @hocamachoc then that would be really useful!

**Comment by hocamachoc** [comment]
Hi @joezuntz, thanks a lot for the contact and for pointing me to the branch. I'll really like to take this forward from where it is. If it's OK, you can assign it to me.

**Comment by joezuntz** [comment]
Perfect, thanks!  I've assigned you.  

Code is on the branch `namaster-cov` in the file `txpipe/twopoint_fourier.py` - in the start I made I pulled out the bits that were common to both two-point estimation and covariance estimation to a base class, and made a start on `TXNamasterCovariance` at the bottom.  So far I'm computing blocks, but not doing anything with them - you'll need to figur out the right ordering and then open (using `self.open_input`) an existing sacc file of the kind output from `TXTwoPointFourier` and add a covariance to it. Figuring out the ordering will be a pain!  Please do ask questions here or on slack if useful!

It's definitely worth setting the `cache` parameter when running - it saves the coupling matrices on the first run, and then it's way faster the second time.

**Comment by joezuntz** [comment]
This is in via TJPCov.
