### ISSUE TITLE
Possibility of bypassing photo-z stacking when using external photo-z

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/TXPipe#97]
Currently, as far as I know, you have to mock up the `PZPDFMLZ` stage and create the `lens_photoz_stack` and `source_photoz_stack` files with the external photo-z to be able to run the two point stages. Is there a way around this? Would it be useful to implement a stage that, in the case of having an input photo-z and N(z), it generates the `photoz_stack` files and bypasses `PZPDFMLZ` and `PhotozStack`? (Something like `ExternalNz`?)

**Comment by aimalz** [comment]
I think we'd discussed this before in the context of #14, to make the stages generic enough to separate estimating photo-zs and/or photo-z posteriors and deriving N(z) however you want from a set of possible inputs (i.e. beyond just photometry).  I think this structural issue might be a prerequisite to #1 and #99.

**Comment by joezuntz** [comment]
There are tools to make this simpler from the redmagic_lens merge.

**Comment by fjaviersanchez** [comment]
@joezuntz, thanks! I think that's right, at least to the extent that the reanalysis projects need this. We can close this for now and discuss possible developments related to #1 / #14 / #99 in those issues.
