### ISSUE TITLE
Use observing condition maps in the two point stages

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/TXPipe#98]
@ellison-j and @zdu863 are working on using externally-provided observing condition maps to deproject in the `TwoPointFourier` stage. Using this issue to track progress.

**Comment by fjaviersanchez** [comment]
A question for @joezuntz, @damonge, and @anicola: how would we want to add these in real space? Using the method here: https://arxiv.org/pdf/1507.05360.pdf or do we want something "fancier"?

**Comment by damonge** [comment]
That's the standard, I think. In Fourier space we can also quantify the bias to the power spectrum caused by deprojecting the systematics, which is still lacking in real space (this is something that Erika Wagoner and Eduardo Rozo were working on though)

**Comment by damonge** [comment]
@fjaviersanchez should the sky mask be provided together with these? Or is this something that TXPipe currently generates itself? I think we discussed this in Arizona, but I forget what we decided

**Comment by fjaviersanchez** [comment]
Currently, the mask is created within TXPipe using the depth map generated using the HSC-DR1 method. Maybe we should open another issue to add the ability to read an externally-provided mask/depth map?

**Comment by damonge** [comment]
I think we should, because this is not gonna have any information about actual survey geometry (e.g. pixel fractions that have actually been observed), right?

**Comment by damonge** [comment]
And then the product of this issue and the issue you propose should be eventually upgraded to generate systematic maps and mask ready for 2-point calculation from the supreme inputs (but that can be done later)

**Comment by fjaviersanchez** [comment]
Agreed! I think that for this issue we just want to add something that points to a place where the maps live (repo/directory) and these are passed as healpix maps or flat-sky maps to `NaMaster`. The former can easily be done by `supréme` (or by Zilong's tools). The latter would require some fiddling (essentially remapping `healsparse` to flat sky maps) but in any case, this is something that goes beyond this repo/issue.

**Comment by damonge** [comment]
I agree.
I think flat-sky stuff is gonna be phased out anyway, so I wouldn't spend cycles on it.

**Comment by ellison-j** [comment]
Sounds good.
At the moment, I am converting our healsparse maps to Healpix format, writing to a fits file then reading into TXPipe. This is because healsparse is not available in Joe's shifter image (`shifter --image docker:joezuntz/txpipe bash`) and `pip install` does not work in the shifter environment. @joezuntz is it possible to include healspase in the environment?

**Comment by ellison-j** [comment]
I have tested the deprojection with the dr1b data and systematic maps using the latest master version and have put my code in a new branch:  u/ellison/syst_deproject

The deprojection code loops over all maps in a given directory (currently `/global/cfs/cdirs/lsst/groups/LSS/DC2_R2.1i/systmaps/txpipe/nc`).

Currently only deprojection for number counts is implemented.

To turn on deprojection use the following in the config file settings for TXTwoPointFourier:
```
    syst_nc: True
    systmaps_nc_dir: /global/cfs/cdirs/lsst/groups/LSS/DC2_R2.1i/systmaps/txpipe/nc
```

You can run using the 'examples/dr1b_pipeline.yml' file.

Here are some plots. Deprojection with one map and 2 maps:
![plot_diag_dp_2maps](https://user-images.githubusercontent.com/26935923/91102196-8fd89f80-e61d-11ea-9596-6e11fa0da12d.jpg)

Deprojection with one map and 4 maps:
![plot_diag_dp_4maps](https://user-images.githubusercontent.com/26935923/91130012-ccc58600-e65f-11ea-9c05-e17e7a8baa5d.jpg)

I have noticed that the TXTwoPointFourier stage (before adding my deprojection code) runs significantly slower than it was running when I was using Javi's branch (u/fjaviersanchez/fixes_2.1i). I am not sure why.

**Comment by joezuntz** [comment]
I think this should have been closed a while back
